version: "2.1"
services:
  SS-TD2:
    container_name: SS-TD2
    image: td2
    restart: always
    build: .
    ports:
      - "3011:3011"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"