version: '3.7'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
  td2:
    build:
      context: './td2'
    container_name: td2
    ports: 
      - "3000:3000"
    depends_on:
      - db
  td3:
    build:
      context: './td3/server'
    container_name: 'td3'  
    ports:
      - "4000:4000" 
    depends_on:
      - td2

